version: '3.8'

services:
  sonarqube:
    image: sonarqube:latest
    ports:
      - "9010:9000"
      - "9011:9092"
    networks:
      - devops-network
    environment:
      - SONARQUBE_JDBC_USERNAME=admin
      - SONARQUBE_JDBC_PASSWORD=Password12@@

  nexus:
    image: sonatype/nexus3:latest
    ports:
      - "8091:8081"
    networks:
      - devops-network
    volumes:
      - nexus-data:/nexus-data

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1337:8089"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devops
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
    networks:
      - devops-network

  mysql:
    image: mysql
    container_name: mysqlSpring

    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3310:3306"
    networks:
      - devops-network

networks:
  devops-network:
    driver: bridge

volumes:
  mysql-data:
  nexus-data: